language: node_js
node_js:
  - "10.4.0"
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    # These variables are for the "staging" branch.
    - STAGING_API_ENDPOINT="https://api.hackillinois.org"
    - STAGING_BASE_URL="https://test.hackillinois.org"

    # These variables are for the "master" branch.
    - MASTER_API_ENDPOINT="https://api.hackillinois.org"
    - MASTER_BASE_URL="https://hackillinois.org"

    # These variables are for all other branches.
    - DEFAULT_API_ENDPOINT="https://api.hackillinois.org"
    - DEFAULT_BASE_URL="https://hackillinois.org"
before_script:
  - |
      if [ "$TRAVIS_BRANCH" = "staging" ]; then
        for prefixed_envvar in ${!STAGING_*}; do
          eval export ${prefixed_envvar#STAGING_}="${!prefixed_envvar}"
        done
      elif [ "$TRAVIS_BRANCH" = "master" ]; then
        for prefixed_envvar in ${!MASTER_*}; do
          eval export ${prefixed_envvar#MASTER_}="${!prefixed_envvar}"
        done
      else
        for prefixed_envvar in ${!DEFAULT_*}; do
          eval export ${prefixed_envvar#DEFAULT_}="${!prefixed_envvar}"
        done
      fi
  - npm install
script:
  - yarn build
deploy:
 - provider: s3
   access_key_id: $HACKILLINOIS_ACCESS_KEY
   secret_access_key: $HACKILLINOIS_SECRET_KEY
   bucket: $HACKILLINOIS_BUCKET_NAME
   skip_cleanup: true
   local_dir: build
   on:
    branch: master
 - provider: s3
   access_key_id: $HACKILLINOIS_ACCESS_KEY
   secret_access_key: $HACKILLINOIS_SECRET_KEY
   bucket: $HACKILLINOIS_TEST_BUCKET_NAME
   skip_cleanup: true
   local_dir: build
   on:
    branch: staging
